### PR TITLE
Upgrade tycho pomless to 1.5.1 / Remove all trivial pom-files

### PR DESCRIPTION
**Pull request by laeubi**
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.vogella.tycho.configuration .................... SUCCESS [  0.058 s]
[INFO] com.vogella.tycho.root ............................. SUCCESS [  0.423 s]
[INFO] bundles ............................................ SUCCESS [  0.001 s]
[INFO] Logging Config ..................................... SUCCESS [  1.569 s]
[INFO] Plugin1 ............................................ SUCCESS [  0.128 s]
[INFO] Ui ................................................. SUCCESS [  0.170 s]
[INFO] com.vogella.tycho.help ............................. SUCCESS [  1.761 s]
[INFO] Rcp ................................................ SUCCESS [  0.090 s]
[INFO] features ........................................... SUCCESS [  0.001 s]
[INFO] Feature ............................................ SUCCESS [  0.087 s]
[INFO] releng ............................................. SUCCESS [  0.001 s]
[INFO] com.vogella.tycho.rcp .............................. SUCCESS [  9.442 s]
[INFO] com.vogella.tycho.target ........................... SUCCESS [  0.001 s]
[INFO] com.vogella.tycho.update.eclipse-repository ........ SUCCESS [  0.942 s]
[INFO] tests .............................................. SUCCESS [  0.001 s]
[INFO] Plugin1 Tests ...................................... SUCCESS [  2.067 s]
[INFO] com.vogella.tycho.rcp.it.tests ..................... SUCCESS [  3.705 s]
[INFO] Tests .............................................. SUCCESS [  1.995 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.033 s
[INFO] Finished at: 2019-11-08T11:09:17+01:00
[INFO] Final Memory: 119M/2181M
[INFO] ------------------------------------------------------------------------
```

Until now, 7 poms off, if you like to merge the ./releng/com.vogella.tycho.configuration into the root pom it would be even one more pom-less. Itest and documentation using excessive configuration and thus stay as is at the moment.

### CODE REVIEW

**Comment by vogella** [comment]
I blindly merged but now I get an error during the build:

vogella@vogella-ThinkPad-T570:~/git/tycho-example$ mvn clean verify
[INFO] Scanning for projects...
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.logging.config/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.tycho.p2.ui/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.tycho.platform/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.tycho.platform.linux/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.tycho.plugin1/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/bundles/com.vogella.tycho.rcp/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/bundles/.polyglot.pom.tycho
/home/vogella/git/tycho-example/features/.polyglot.pom.tycho
/home/vogella/git/tycho-example/features/com.vogella.tycho.feature/.polyglot.feature.xml.takari_issue_192
/home/vogella/git/tycho-example/features/.polyglot.pom.tycho
/home/vogella/git/tycho-example/features/.polyglot.pom.tycho
/home/vogella/git/tycho-example/releng/.polyglot.pom.tycho
/home/vogella/git/tycho-example/releng/com.vogella.tycho.product/.polyglot.com.vogella.tycho.rcp.product
/home/vogella/git/tycho-example/releng/.polyglot.pom.tycho
/home/vogella/git/tycho-example/releng/.polyglot.pom.tycho
/home/vogella/git/tycho-example/releng/com.vogella.tycho.target/.polyglot.com.vogella.tycho.target.target
/home/vogella/git/tycho-example/releng/.polyglot.pom.tycho
/home/vogella/git/tycho-example/releng/com.vogella.tycho.update/.polyglot.category.xml.takari_issue_192
/home/vogella/git/tycho-example/releng/.polyglot.pom.tycho
/home/vogella/git/tycho-example/tests/.polyglot.pom.tycho
/home/vogella/git/tycho-example/tests/com.vogella.tycho.plugin1.tests/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/tests/.polyglot.pom.tycho
/home/vogella/git/tycho-example/tests/.polyglot.pom.tycho
/home/vogella/git/tycho-example/tests/com.vogella.tycho.rcp.tests/.polyglot..META-INF_MANIFEST.MF
/home/vogella/git/tycho-example/tests/.polyglot.pom.tycho
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.help:[unknown-version]: Could not find artifact com.vogella.tycho:bundles:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.rcp.it.tests:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:tests:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 10
[WARNING] 'build.plugins.plugin.version' for org.eclipse.tycho:tycho-p2-director-plugin is missing. @ 
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.help:[unknown-version] (/home/vogella/git/tycho-example/bundles/com.vogella.tycho.help/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.help:[unknown-version]: Could not find artifact com.vogella.tycho:bundles:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.rcp.it.tests:1.0.0-SNAPSHOT (/home/vogella/git/tycho-example/tests/com.vogella.tycho.rcp.it.tests/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.rcp.it.tests:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:tests:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by vogella** [comment]
Also Travis does not like this change. https://travis-ci.org/vogellacompany/tycho-example?utm_medium=notification&utm_source=email

**Comment by laeubi** [comment]
Travis says
`Failed to generate toc file: /home/travis/build/vogellacompany/tycho-example/bundles/com.vogella.tycho.help/help/api-docs/javadoc/element-list (No such file or directory)` no idea what that means, but I'll pull the change and see what might be wrong

**Comment by laeubi** [comment]
maven 3.3.9 from eclipse > works
maven 3.5.4 commandline > fails

**Comment by laeubi** [comment]
Okay can you replace in bundles/com.vogella.tycho.help/pom.xml and vogella-tycho-example/tests/com.vogella.tycho.rcp.it.tests relativePath with?
`<relativePath>../.polyglot.pom.tycho</relativePath>`
See commit https://github.com/laeubi/tycho-example/commit/cf0c01e6bb8decd8effa0a92f6e53931492bb783

**Comment by vogella** [comment]
This works but feels strange. Is this a workaround for a bug?

**Comment by laeubi** [comment]
One might want to call it a feature instead ... i honestly don't know what the maven guys are doing so there is such great difference between versions...

**Pull request merged**
