### PR TITLE
Adjust to new Tycho 1.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by laeubi**
This shows how you can omit even more pom files with the new tycho 1.5 release

### CODE REVIEW

**Comment by vogella** [comment]
Thanks. Cool. Not sure why the build fails, I pull it locally and will test.

**Comment by laeubi** [comment]
Seems it no longer supports java8 : Expected feature release number in range of 9 to 14, but got: 8
You need to have SNAPSHOTs configured and there is one small issue that needs to be merged before it will work: https://git.eclipse.org/r/#/c/148432/

**Comment by vogella** [comment]
What? Even the bundles poms are not required anymore? Coooooooooool. I push a new PR to use this, this one is outdated (my fault).

**Comment by vogella** [comment]
If I delete the bundles/pom.xml I get an error.

**Comment by laeubi** [comment]
Its been some time, let me check if I can update the example. Essentially only one pom is required at all but that detepnds a little on the desired build structure.

**Comment by vogella** [comment]
Looking forward to your PR, my attempt to delete the product pom file was not successful.

**Comment by laeubi** [comment]
In favor of a new PR

**Pull request closed without merging**
