### PR TITLE
Re-enable RCP integration tests

### PR DESCRIPTION
**Pull request by howlger**
Re-enable RCP integration tests provided by the [`com.vogella.tycho.rcp.it.tests`](https://github.com/vogellacompany/tycho-example/tree/master/tests/com.vogella.tycho.rcp.it.tests) fragment.

### CODE REVIEW

**Comment by vogella** [comment]
Build fails. @howlger please have a look.

**Comment by howlger** [comment]
> Build fails. @howlger please have a look.

Works fine for me on my local computer. I tried to rebase, but now the invalid `.github/workflows/maven.yaml` file causes the build to fail (which is unrelated to this pull request):
> GitHub Actions / .github/workflows/maven.yaml
> Invalid workflow file
> You have an error in your yaml syntax on line 17

**Comment by howlger** [comment]
@vogella I guess you're right. Could you please take over?

**Comment by vogella** [comment]
@howlger not sure when I will find the time for that....

**Comment by howlger** [comment]
Property `skip.ui-tests` added and used in the GitHub action to skip the UI tests (`mvn verify -Dskip.ui-tests=true`). So the integration tests are run by default, but not in the GitHub action. Enabling them in the GitHub action (by run them in a container) could be done in a separate task.

**Comment by vogella** [comment]
Thanks, @howlger

**Pull request merged**
